config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :holdings
  resources :coins do
    get :chart_data, on: :member
  end
  resources :portfolios
  resources :transactions

  root to: "portfolios#index"

  get "quick_add", to: "quick_add#new", as: :quick_add
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/holding.rb
class Holding < ApplicationRecord
  belongs_to :coin, foreign_key: 'coin_id', class_name: 'Coin'
  belongs_to :portfolio, foreign_key: 'portfolio_id', class_name: 'Portfolio'

  validates :coin_id, uniqueness: { scope: :portfolio_id }
  validates :portfolio_id, uniqueness: { scope: :coin_id }
  validates :coin_balance, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def to_s
    "
    Holding ID: #{id},
    Coin: #{coin.id},
    Portfolio: #{portfolio.id},
    Coin Balance: #{coin_balance.to_s('F')}
    ".squish
  end
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  before_action :set_holding, only: %i[ show edit update destroy ]

  # GET /holdings or /holdings.json
  def index
    @holdings = Holding.all
  end

  # GET /holdings/1 or /holdings/1.json
  def show
  end

  # GET /holdings/new
  def new
    @holding = Holding.new
  end

  # GET /holdings/1/edit
  def edit
  end

  # POST /holdings or /holdings.json
  def create
    @holding = Holding.new(holding_params)

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding, notice: "Holding was successfully created." }
        format.json { render :show, status: :created, location: @holding }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /holdings/1 or /holdings/1.json
  def update
    respond_to do |format|
      if @holding.update(holding_params)
        format.html { redirect_to @holding, notice: "Holding was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @holding }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1 or /holdings/1.json
  def destroy
    @holding.destroy!

    respond_to do |format|
      format.html { redirect_to holdings_path, notice: "Holding was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_holding
      @holding = Holding.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def holding_params
      params.fetch(:holding, {})
    end
end

app/helpers/holdings_helper.rb
module HoldingsHelper
end

app/views/holdings/_form.html.erb
<%= form_with(model: holding) do |form| %>
  <% if holding.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(holding.errors.count, "error") %> prohibited this holding from being saved:</h2>

      <ul>
        <% holding.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/holdings/_holding.html.erb
<div id="<%= dom_id holding %>">
</div>

app/views/holdings/edit.html.erb
<% content_for :title, "Editing holding" %>

<h1>Editing holding</h1>

<%= render "form", holding: @holding %>

<br>

<div>
  <%= link_to "Show this holding", @holding %> |
  <%= link_to "Back to holdings", holdings_path %>
</div>

app/views/holdings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Holdings" %>

<h1>Holdings</h1>

<div id="holdings">
  <% @holdings.each do |holding| %>
    <%= render holding %>
    <p>
      <%= link_to "Show this holding", holding %>
    </p>
  <% end %>
</div>

<%= link_to "New holding", new_holding_path %>

app/views/holdings/new.html.erb
<% content_for :title, "New holding" %>

<h1>New holding</h1>

<%= render "form", holding: @holding %>

<br>

<div>
  <%= link_to "Back to holdings", holdings_path %>
</div>

app/views/holdings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @holding %>

<div>
  <%= link_to "Edit this holding", edit_holding_path(@holding) %> |
  <%= link_to "Back to holdings", holdings_path %>

  <%= button_to "Destroy this holding", @holding, method: :delete %>
</div>