config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :holdings
  resources :coins do
    get :chart_data, on: :member
  end
  resources :portfolios
  resources :transactions

  root to: "portfolios#index"

  get "quick_add", to: "quick_add#new", as: :quick_add
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_footer.html.erb
<div class="spacer"></div>
<div class="footer glass">
  <p class="footer-text">&copy; <%= Time.current.year %> Tracker App.</p>
  <p class="footer-text">All rights reserved.</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar glass">
  <h2><%= link_to 'Tracker', portfolios_path, class: "nav-title #{nav_list_active?(portfolios_path)}" %></h2>
  <% if user_signed_in? %>
    <div class="nav-links-container">
      <p><%= link_to nav_label('Portfolios', portfolios_path), portfolios_path, class: "nav-link #{nav_list_active?(portfolios_path)}" %></p>
      <p><%= link_to nav_label('Coins', coins_path), coins_path, class: "nav-link #{nav_list_active?(coins_path)}" %></p>
      <p><%= link_to nav_label('Transactions', transactions_path), transactions_path, class: "nav-link #{nav_list_active?(transactions_path)}" %></p>
      <p><%= link_to nav_label('Create', quick_add_path), quick_add_path, class: "nav-link #{nav_list_active?(quick_add_path)}" %></p>
    </div>
    <p><%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-logout #{nav_list_active?(destroy_user_session_path)}" %></p>
  <% else %>
    <p><%= link_to 'Login', new_user_session_path, class: "nav-link #{nav_list_active?(new_user_session_path)}" %></p>
  <% end %>
</nav>

app/views/layouts/_search_bar.html.erb
<%= form_with(url: coins_path, method: :get, local: true) do %>
    <div class="search-field">
        <%= label_tag :name, 'Search:' %>
        <%= text_field_tag :name, params[:name], class: 'search-bar' %>
        <%= hidden_field_tag :sort_by, params[:sort_by] %>
        <%= hidden_field_tag :dir, params[:dir] %>
        <%= submit_tag 'Search', class: 'btn' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tracker App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice || alert %>
      <p class="<%= alert ? 'alert' : 'notice' %>"><%= notice || alert %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>